export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_USER_ROUTINES = 'GET_USER_ROUTINES';
export const GET_USER_DAY_ROUTINES = 'GET_USER_DAY_ROUTINES';
export const GET_USER_GOALS = 'GET_USER_GOALS';

